version: '2'
services:
  #######################################
  # Application
  #######################################
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    depends_on:
      - db
      - mail
    links:
      - db
      - mail
    volumes:
      - ./app:/var/www/html/
    environment:
      - DB_NAME=wp
      - DB_USER=wp
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PREFIX=wp_
      - WP_ENV=development
      - WP_HOME=http://$PROJECT_NAME.docker
      - WP_SITEURL=http://$PROJECT_NAME.docker/wp
    extra_hosts:
      - "api.wordpress.org:66.155.40.187"
      - "downloads.wordpress.org:66.155.40.203"

  #######################################
  # Webserver
  #######################################
  web:
    image: nginx:alpine
    volumes:
      - ./.docker/web/h5bp:/etc/nginx/h5bp
      - ./.docker/web/fastcgi_params:/etc/nginx/fastcgi_params
      - ./.docker/web/mime.types:/etc/nginx/mime.types
      - ./.docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/web/site.conf.template:/etc/nginx/site.conf.template
    depends_on:
      - app
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST=$PROJECT_NAME.docker
      - VIRTUAL_PORT=80
    # substitute hostname to nginx conf; syntax from here: https://github.com/docker-library/docs/issues/496#issuecomment-203003827
    command: /bin/sh -c "envsubst '$$VIRTUAL_HOST' < /etc/nginx/site.conf.template > /etc/nginx/site.conf && cat /etc/nginx/site.conf && nginx -g 'daemon off;'"

  #######################################
  # Database
  #######################################
  # Enable port mapping to access the database via
  # host: localhost
  # port: 3306
  #######################################
  db:
    image: mariadb
#    ports:
#      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=password

  #######################################
  # phpMyAdmin
  #######################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    links:
      - db
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=phpmyadmin.$PROJECT_NAME.docker
      - PMA_ABSOLUTE_URI=http://phpmyadmin.$PROJECT_NAME.docker/
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=wp
      - PMA_PASSWORD=password

  #######################################
  # Mailhog
  #######################################
  mail:
    image: mailhog/mailhog
    environment:
      - VIRTUAL_PORT=8025
      - VIRTUAL_HOST=mail.$PROJECT_NAME.docker
